ops:
  load_sklearn_model:
    config:
      model_uri: models:/wine_rfc/2
  sklearn_to_onnx:
    config:
      input_type: float_input
      input_shape: [None, 11]
  publish_to_mlflow:
    config:
      registered_model_name: wine_rfc_onnx
  deploy_to_triton:
    config:
      registered_model_name: wine_rfc_onnx
resources:
  mlflow:
    config:
      experiment_name: "wine_rfc"
      mlflow_tracking_uri: ${MLFLOW_TRACKING_URI:"http://mlflow_server:4000"}

      env:
        MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL:"http://minio:9000"}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:"minio_user"}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:"minio_password"}
        TRITON_URL: ${TRITON_URL:"http://triton-server:8000"}
        TRITON_MODEL_REPO: ${TRITON_MODEL_REPO:"s3://minio:9000/triton"}
