ops:
  load_mlflow_model:
    config:
      model_uri: models:/wine-rfc/2
  create_service:
    config:
      service_name: WineRFC
  pack_model:
    config:
      python_version: 3.8.13
  upload_service:
    config:
      s3_endpoint: http://minio:9000
      bucket_name: bento
  run_image:
    config:
      hostname: winerfc
      port: 5000
      network: mlops_bridge
resources:
  mlflow:
    config:
      experiment_name: wine_rfc
      mlflow_tracking_uri: http://mlflow-server:4000
      env:
        MLFLOW_S3_ENDPOINT_URL: http://minio:9000
        AWS_ACCESS_KEY_ID: minio_user
        AWS_SECRET_ACCESS_KEY: minio_password
