ops:
  download_dataset:
    config:
      url: "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv"
  split_data:
    config:
      test_size: 0.2
  train_rfc:
    config:
      n_estimators: 50
      max_depth: 10
resources:
  mlflow:
    config:
      experiment_name: "wine_rfc"
      mlflow_tracking_uri: ${MLFLOW_TRACKING_URI:"http://localhost:5000"}

      env:
        MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL}
        AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
        AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
